### ISSUE TITLE
"Variability Index" doesn't show in non-premium

### ISSUE THREAD

**Issue by jonnylamb** [lamby/strava-enhancement-suite#30]
I don't have premium and I guess that's the reason "Variability Index" doesn't show. Would be cool to have, but a comment that it's unsupported would also be cool!

**Comment by lamby** [comment]
Would you expect to see it even without a power meter?

(Genuine question; could be just a docs issue)

**Comment by jonnylamb** [comment]
Ah, fair, I just read the docs properly. I assumed it would be possible for pacing in a run too.

Feel free to close this as RESOLVED READTHEDOCS

**Comment by lamby** [comment]
Added something about a power meter.
