### ISSUE TITLE
Add option to disable map/image zooming

### ISSUE THREAD

**Issue by jonnylamb** [lamby/strava-enhancement-suite#31]
There should be an option for disabling the zooming in when you hover over an athlete picture or map.

**Comment by lamby** [comment]
Is this not "enlarge on hover" ?

**Comment by jonnylamb** [comment]
Huh, sorry about that, completely didn't see it. However:

![schermata da 2015-03-10 21 27 45](https://cloud.githubusercontent.com/assets/1036038/6584576/8b1a1a6c-c76c-11e4-88aa-e57b9f72e0f5.png)

and yet:

![schermata da 2015-03-10 21 27 52](https://cloud.githubusercontent.com/assets/1036038/6584577/8d463aaa-c76c-11e4-9bcf-6aae849b7fc0.png)

(pointer is over the avatar)

**Comment by lamby** [comment]
> However

Can't reproduce that unfortunately.

**Comment by lamby** [comment]
Assuming is fixed, otherwise please re-open :)
