### ISSUE TITLE
User's Premium badge hidden in error?

### ISSUE THREAD

**Issue by mkns** [lamby/strava-enhancement-suite#33]
Hi,

In the Dashboard, a Premium user will (should) have a Premium badge next to their name. Unfortunately, this is hidden if the Strava Enhancement Suite's 'Hide Find Friends' option is turned on.

IMHO, this is a bug. However, from looking at the source, it may not be, because there's clearly a bit of code underneath the comment 'Remove "Premium" buttons' that does just what the comment suggests when this option is turned on. I have no clue why this should be hidden if the Hide Find Friends option is turned on, though, so figure it might be there by accident and thought it was worth asking the question.

**Comment by lamby** [comment]
Personally I dislike the premium badges (it's under the same revenue-begging *mental* category of the "find friends" features) hence why they are hidden. I would concede it is poorly named and/or documented, of course.

Are you asking for a separate option for this?

**Comment by mkns** [comment]
Not really, I have resolved the problem by unchecking the feature. For no apparently good reason, it's bothered me for weeks, and I finally decided to go through each option and toggling them to find out which one it was that was hiding the badges. Now I've found it, I'll just keep the option turned off, as for no good reason, I think it's fair enough to see who are Premium users. I'm one now because of Live Strava Segments on the Garmin Edge (which is ridiculously awesome, btw).

Therefore, if you're looking for an opinion, I'd just document it. I suppose some people might want a separate option for it, but I'm not particularly bothered. If you *did* have a separate option, though, I'd hide the Find Friends nonsense and keep the badges.

**Comment by lamby** [comment]
FYI "Are you asking for" is a kinda free-software shorthand for "what would your solution be in an ideal world". I mean, you hardly created this bug simply to mention that fixed it by yourself and now everything is fine. ;)

**Comment by mkns** [comment]
Oh, ok, didn't realise that. I didn't want to come across as someone who allegedly thought they knew better than you what your tool should do. I have people who do that to me occasionally, and it irritates me. So, the ideal solution AFAIAC would probably be two options. Having an option which only hides the Premium badges seems a little OTT, but since I'd like to see those badges while hiding the Find Friends thing, two options would be my ideal scenario.

(FYI I created the bug in case you hadn't realised you'd left that block of code in another option by accident, while recognizing that you may well have done that deliberately)

**Comment by lamby** [comment]
No worries at all - thanks for bringing it up :) Will get onto this when I do another round of changes, it's no bother to add a new option and it might avoid Strava Inc. get antsy for a bit longer...

**Comment by mkns** [comment]
Cool, thanks \o/

It's a great tool, btw. The infinite scroll feature on its own is reason enough to have it installed!

(Should I close this now, or do you do that later? I'm such a n00b)

**Comment by lamby** [comment]
no, please leave it open - I will close it when fixed

**Comment by lamby** [comment]
Fixed in https://github.com/lamby/strava-enhancement-suite/commit/0b5db9cecff48be10445d2274ed459ae4ffec2bf

**Comment by mkns** [comment]
Thanks :) \o/
