### ISSUE TITLE
Best Splits are wrong/inconsistent

### ISSUE THREAD

**Issue by Langlaeufer** [lamby/strava-enhancement-suite#38]
The results of "best minute" and "best Km" are not consistent.

For example: https://www.strava.com/activities/433205779
If my best minute is 0,75 km at 40 km/h then my best km can't be faster 1:14 at 49 km/h
both should be at 44 km/h - i never reached 49 km/h at the shown place

**Comment by lamby** [comment]
That is part of Strava itself, not the enhancement suite so out of my control. Sorry :)

**Comment by Langlaeufer** [comment]
Strava shows a max - speed of 48 km /h. The speed graph seems to be correct.

When the best split function shows wrong values, than it is not helpful. It does'nt matter if it is your bug or a problem of strava!

**Comment by lamby** [comment]
> When the best split function shows wrong values, than it is not helpful. It does'nt matter if it is your bug or a problem of strava!

Right, but I am not sure what you think I can do about it?

**Comment by Langlaeufer** [comment]
I would deactivate/remove the function. If it is a bug of the API, I would report this to Strava an wait till it is solved.

**Comment by lamby** [comment]
> I would deactivate/remove the function

But this is not a function in Strava Enhancement Suite..

**Comment by Langlaeufer** [comment]
oh sorry - i mixed it - it is StravistiX
