### ISSUE TITLE
Issue with Hover Mode in Google Chrome

### ISSUE THREAD

**Issue by Abeldecos** [lamby/strava-enhancement-suite#53]
Using the most current update of Strava, the Strava Enhancement Suite is acting odd in my Chrome browser. If I hover over the map on the Feed page, the map flashes, and I can not pick it. If I move the cursor to the left side of the map image it shrinks to half size and I can pick it. Not an issue with Explorer or Edge.

I have determined that it is the "Hover Mode" that is causing the issue. Disabling that option fixes the issue.

System Info:
Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)
Dell XPS 8700 & Surface Pro 3 (Both have issue)
Windows 10 Pro - Most Current version update
Graphic Card - GeForce GTX 970 / Driver 388.00 (Dell)
Three monitor set-up with Dell - Same issue on any of the monitors

**Comment by lamby** [comment]
Closed in #56.
