### ISSUE TITLE
Zwift activities not being removed from feed.

### ISSUE THREAD

**Issue by ChrisHeerschap** [lamby/strava-enhancement-suite#54]
Running Chrome 63.0.3239.84 (Official Build) (64-bit) on Mac OS X 10.12.6 with SES from the Chrome store. I've got the option to hide Zwift activities checked:
![screen shot 2017-12-18 at 9 58 40 am](https://user-images.githubusercontent.com/3670938/34112339-46d86696-e3da-11e7-8b60-86ab339cb0a4.png)

but I'm still getting Zwift activities:
![screen shot 2017-12-18 at 9 59 05 am](https://user-images.githubusercontent.com/3670938/34112340-46e5903c-e3da-11e7-9c07-faebb314eae2.png)

and I'm getting trainer activities without maps:
![screen shot 2017-12-18 at 10 01 52 am](https://user-images.githubusercontent.com/3670938/34112469-a1f9de7e-e3da-11e7-9de9-c14b6f2ad3f2.png)

Please let me know if there's any more information I can supply for debugging this. Thanks!

**Comment by lamby** [comment]
@ChrisHeerschap Can you provide the `.feed-entry` HTML? :)

**Comment by ChrisHeerschap** [comment]
Gladly - but I'm not sure where to get that. Apologies if I missed any doc on submitting issues, I read the readme but didn't see anything else.

**Comment by lamby** [comment]
@ChrisHeerschap Do you know how to use the Chrome DOM inspector tool? :)

**Comment by ChrisHeerschap** [comment]
If you mean the developer tools that opens with a command-option-I, I am aware of it and make very limited use of it but really don't know what I'm doing when I have it open. If it's something else, then I have no idea.

**Comment by ChrisHeerschap** [comment]
Thanks, hit close by accident.

**Comment by lamby** [comment]
@ChrisHeerschap 
No, lets keep this open - I can find the HTML myself, just wondering if you had it handy!

(it's via right-clicking on the page and pressing **Inspect**).

**Comment by ChrisHeerschap** [comment]
Ah, okay, looks like the same panel. Unsure where to find the .feed-entry HTML past that.

**Comment by lamby** [comment]
Well, if you inspect the offending feed item, just scroll up the tree until you see the `<div>` that has `feed-entry` in the class, then right-click, copy as HTML :)

**Comment by ChrisHeerschap** [comment]
Okay, here's one of the offending items:
https://gist.github.com/ChrisHeerschap/6d3a9a027d7dac9ca8292db78283703e

**Comment by ChrisHeerschap** [comment]
...and a Zwift entry:
https://gist.github.com/ChrisHeerschap/897553ccedc691211cb80888a4d706c7

Is that useful?

**Comment by lamby** [comment]
Thanks. If there are other issues, please file each type of offending item as a different, separate ticket. :)  o/

**Comment by ChrisHeerschap** [comment]
Just the one issue - Zwift and trainer rides showing up despite the option to remove them being checked. So the HTML was helpful?

**Comment by lamby** [comment]
Yes, HTML was useful - thanks!

^ and please, separate tickets with screenshots/HTML for separate issues..

**Comment by ChrisHeerschap** [comment]
As I see it, it's one option that isn't working - not seeing this as separate issues, just multiple instances of things not caught by the one option. Including several instances of things that should be blocked. Apologies if these would be viewed as separate issues.

**Comment by lamby** [comment]
@ChrisHeerschap No problem. :)  Grumble at Zwift ;)
