### ISSUE TITLE
Layout issue with external links

### ISSUE THREAD

**Issue by grit96** [lamby/strava-enhancement-suite#56]
With external links enabled there is a layout issue on activity pages I haven't kudoed.

![image](https://user-images.githubusercontent.com/3957608/52276615-95db3280-294a-11e9-925f-29aaa46ee3bd.png)

As a side-note, Raceshape has shut down so should probably be removed.
(https://support.strava.com/hc/en-us/community/posts/208135228-Raceshape-Tools)

**Comment by lamby** [comment]
Closed in #56.
